// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqb14W9WvFR66fVcQ1KON_Sr8t24LogOs',
    appId: '1:760632240896:web:a19e11220f4e0948bb21e5',
    messagingSenderId: '760632240896',
    projectId: 'flutternotes-1870a',
    authDomain: 'flutternotes-1870a.firebaseapp.com',
    storageBucket: 'flutternotes-1870a.firebasestorage.app',
    measurementId: 'G-26J9Z3LF4Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBss5bZ4t0nTLNw4QlO_xwUV8rC8yMZAkA',
    appId: '1:760632240896:android:a1fd2df91e90d990bb21e5',
    messagingSenderId: '760632240896',
    projectId: 'flutternotes-1870a',
    storageBucket: 'flutternotes-1870a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS45wDgRx2RSfCT_A8e-jTkDEAd-qkwYc',
    appId: '1:760632240896:ios:d1bc50b53aeea8e8bb21e5',
    messagingSenderId: '760632240896',
    projectId: 'flutternotes-1870a',
    storageBucket: 'flutternotes-1870a.firebasestorage.app',
    iosBundleId: 'com.example.flutternotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS45wDgRx2RSfCT_A8e-jTkDEAd-qkwYc',
    appId: '1:760632240896:ios:d1bc50b53aeea8e8bb21e5',
    messagingSenderId: '760632240896',
    projectId: 'flutternotes-1870a',
    storageBucket: 'flutternotes-1870a.firebasestorage.app',
    iosBundleId: 'com.example.flutternotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqb14W9WvFR66fVcQ1KON_Sr8t24LogOs',
    appId: '1:760632240896:web:d9118924fef57a56bb21e5',
    messagingSenderId: '760632240896',
    projectId: 'flutternotes-1870a',
    authDomain: 'flutternotes-1870a.firebaseapp.com',
    storageBucket: 'flutternotes-1870a.firebasestorage.app',
    measurementId: 'G-6XCLYNY57H',
  );
}
